from typing import Protocol

from app.models.domain import Carrier, Communication, Document, ExecutionResult, Shipment, TrackingState
from integrations.ascend.adapter import AscendAdapter as AscendAdapter


class CapabilityUnavailable(RuntimeError):
    pass


class TrackingAdapter(Protocol):
    async def find_shipment(self, external_id: str) -> Shipment: ...
    async def get_tracking_load(self, external_id: str) -> TrackingState: ...
    async def get_tracking_status(self, external_id: str) -> str: ...
    async def get_tracking_acceptance(self, external_id: str) -> bool | None: ...
    async def get_latest_position(self, external_id: str) -> TrackingState: ...
    async def get_tracking_history(self, external_id: str) -> list[TrackingState]: ...
    async def get_eta(self, external_id: str) -> TrackingState: ...
    async def get_driver_messages(self, external_id: str) -> list[Communication]: ...
    async def get_documents(self, external_id: str) -> list[Document]: ...
    async def get_share_link(self, external_id: str) -> str | None: ...
    async def create_tracking_load(self, shipment: Shipment, authorization_id: str) -> ExecutionResult: ...
    async def update_tracking_load(self, shipment: Shipment, authorization_id: str) -> ExecutionResult: ...
    async def initiate_tracking(self, external_id: str, authorization_id: str) -> ExecutionResult: ...
    async def send_tracking_request(self, external_id: str, authorization_id: str) -> ExecutionResult: ...
    async def close_tracking_load(self, external_id: str, authorization_id: str) -> ExecutionResult: ...


class TmsAdapter(Protocol):
    async def find_load(self, external_id: str) -> Shipment: ...
    async def reconcile(self, canonical: Shipment) -> dict: ...
    async def update_load(self, expected: Shipment, intended: Shipment,
                          authorization_id: str) -> ExecutionResult: ...


class MailAdapter(Protocol):
    async def monitor_mailbox(self) -> list[Communication]: ...
    async def read_email(self, message_id: str) -> Communication: ...
    async def search_email(self, query: str) -> list[Communication]: ...
    async def get_attachment(self, message_id: str, attachment_id: str) -> Document: ...
    async def create_draft(self, facts: dict, authorization_id: str) -> ExecutionResult: ...
    async def reply_draft(self, message_id: str, facts: dict, authorization_id: str) -> ExecutionResult: ...
    async def send(self, draft_id: str, authorization_id: str) -> ExecutionResult: ...


class MessagingAdapter(Protocol):
    async def conversations(self, contact_reference: str) -> list[Communication]: ...
    async def send_sms(self, shipment_id: str, verified_facts: dict,
                       authorization_id: str) -> ExecutionResult: ...


class CarrierAdapter(Protocol):
    async def search_carrier(self, mc: str | None, dot: str | None) -> Carrier: ...
    async def get_onboarding_status(self, carrier_id: str) -> str: ...
    async def get_profile(self, carrier_id: str) -> Carrier: ...
    async def get_vetting(self, carrier_id: str) -> dict: ...
    async def get_documents(self, carrier_id: str) -> list[Document]: ...


class LoadBoardAdapter(Protocol):
    async def post_load(self, shipment: Shipment, authorization_id: str) -> ExecutionResult: ...
