(() => {
  'use strict';
  const results=Object.freeze({
    PAIRING_FILE_NOT_SELECTED:'Choose the runtime-local bootstrap file, then click Import selected file.',
    PAIRING_FILE_SELECTED:'File selected. Click Import selected file.',
    PAIRING_FILE_READ_FAILED:'Reselect the local file. Use the persistent pairing panel if needed.',
    PAIRING_SCHEMA_INVALID:'Use the unedited bootstrap generated by the local Pair helper.',
    PAIRING_EXPIRED:'Generate one fresh bootstrap with the local Pair helper and import promptly.',
    PAIRING_ALREADY_CONSUMED:'This bootstrap was used. Generate a fresh one; do not reset the ledger.',
    EXTENSION_ID_MISMATCH:'Check the installed extension ID against local installation configuration.',
    PAIRING_VALIDATING:'Validating the selected bootstrap locally.',
    PAIRING_HANDSHAKE_PENDING:'Waiting for a verified local host acknowledgement.',
    HOST_HANDSHAKE_FAILED:'Check local host reachability. Retry only after resolving this result.',
    PAIRING_PROOF_REJECTED:'Generate a fresh bootstrap from this installation and import it once.',
    PAIRING_DPAPI_FAILED:'Use the Windows account that created this local pairing installation.',
    PAIRING_BINDING_MISMATCH:'The bootstrap does not match the current local pairing generation.',
    PAIRING_PERSIST_FAILED:'Check local runtime access. Pairing is not confirmed; do not reuse uncertain material.',
    PAIRING_ACK_INVALID:'Host acknowledgement was not verified. Pairing remains unavailable.',
    PAIRING_INTERRUPTED:'Pairing context was lost. Reopen the panel and check the host; a fresh Pair may be needed.',
    PAIRING_REQUIRED:'Generate a fresh local bootstrap and import it when ready.',
    HOST_REACHABLE:'Local host responded. Pairing is still required.',
    PAIRING_SUCCESS:'Verified local pairing. Reads require a separate host authorization; writes remain blocked.',
    PAIRING_DIAGNOSTIC_SAVED:'Sanitized local diagnostic recorded.',
    COMMAND_NOT_ALLOWED:'Only local pairing controls are available.'
  });
  const stages=Object.freeze(['FILE_INPUT','FILE_READ','JSON_PARSE','SCHEMA_VALIDATION','EXTENSION_ID_VALIDATION',
    'EXPIRY_VALIDATION','NATIVE_CONNECT','DPAPI_VALIDATION','ONE_TIME_VALIDATION','PROOF_VALIDATION',
    'PAIRING_PERSIST','ACK_VERIFICATION','PAIRED','LIFECYCLE']);
  const safe=code=>Object.hasOwn(results,code)?code:'HOST_HANDSHAKE_FAILED';
  const result=(state,code)=>({state,error_code:safe(code),remediation:results[safe(code)]});
  const metadata=(stage,code,flags={})=>{
    const value={handshake_stage:stages.includes(stage)?stage:'LIFECYCLE',result_code:safe(code)};
    for(const key of ['extension_id_match','bootstrap_expired','bootstrap_consumed'])
      if(typeof flags[key]==='boolean')value[key]=flags[key];
    return value;
  };
  globalThis.FreightDeskPairingDiagnostics=Object.freeze({results,stages,safe,result,metadata});
})();
