(() => {
  'use strict';
  const codes=['CONTENT_SCRIPT_MISSING','CONTENT_SCRIPT_OLD_VERSION','CONTENT_SCRIPT_PORT_STALE','DOCUMENT_CHANGED','PROTOCOL_VERSION_MISMATCH','CONTENT_SCRIPT_INJECTION_BLOCKED','CONTENT_SCRIPT_RECOVERY_FAILED','DETAIL_CONTRACT_INVALID','DETAIL_CONTRACT_UNAVAILABLE','DETAIL_CONTAINER_UNVERIFIED','DETAIL_BOUND_CONTAINERS','DETAIL_BOUND_ATTRIBUTES','DETAIL_BOUND_CONTROLS','DETAIL_BOUND_HEADINGS','DETAIL_BOUND_CANDIDATES','DETAIL_BOUND_DEPTH','DETAIL_ATTEMPT_CONSUMED','DETAIL_DISCOVERY_COMPLETE','READ_RELEASE_REQUIRED','READ_POLICY_BLOCKED','READ_TEST_CONSUMED','READ_TEST_EXPIRED','READ_SEQUENCE_INVALID',
    'COMMAND_NOT_ALLOWED','PAIRING_LOST','NO_ELIGIBLE_TAB','TAB_SELECTION_REQUIRED','TAB_STATE_CHANGED','SESSION_UNVERIFIED',
    'ACTIVE_VIEW_UNVERIFIED','ACTIVE_VIEW_CHANGED','ACTIVE_VIEW_NOT_ACTIVE_LOADS','BOARD_SCHEMA_INVALID','BOARD_MISMATCH','BOARD_CHANGED','EXACT_LOAD_MISSING','OPENER_AMBIGUOUS',
    'UNSAFE_OPENER','DETAIL_IDENTITY_MISSING','DETAIL_IDENTITY_AMBIGUOUS','DETAIL_IDENTITY_CONFLICT','IDENTITY_BOUND_EXCEEDED',
    'READ_TIMEOUT','RECEIPT_INVALID','READ_PERSIST_FAILED','READ_EXECUTION_FAILED','DUPLICATE_REQUEST','NAVIGATION_UNVERIFIED','NAVIGATION_STARTED','CONTENT_SCRIPT_STALE','REFRESH_ASCEND_TAB','TAB_DISCOVERY_FAILED'];
  codes.push('NO_FOREGROUND_ASCEND_WORKSPACE','EXPECTED_LOAD_NOT_OPEN','STARTING_SECTION_MISMATCH','NOT_A_LOAD_WORKSPACE','AUTO_MAP_SECTION_UNVERIFIED','MAPPING_CAPTURE_BOUND','MAPPING_CAPTURE_PENDING','MAPPING_COMPLETE','MAPPING_CONTRACT_BOUND','MAPPING_CONTRACT_INVALID','MAPPING_NOT_ENABLED','MAPPING_OWNER_NOT_PRESENT','MAPPING_PAYLOAD_BOUND','MAPPING_SECTION_BOUND','MAPPING_SESSION_CONSUMED','MAPPING_VALIDATION_REQUIRED','MAPPING_WORKSPACE_BOUND','NAVIGATION_CONTRACT_UNVERIFIED','NAVIGATION_CONTROL_AMBIGUOUS','NAVIGATION_CONTROL_CHANGED','WORKSPACE_AMBIGUOUS','WORKSPACE_BOUND','WORKSPACE_CHANGED','WORKSPACE_IDENTITY_CONFLICT','WORKSPACE_IDENTITY_MISSING','WORKSPACE_SCOPE_DENIED','WORKSPACE_SECTION_UNVERIFIED');
  const aliases={session_unverified:'SESSION_UNVERIFIED',origin_denied:'TAB_STATE_CHANGED',active_view_unverified:'ACTIVE_VIEW_UNVERIFIED',
    data_grid_ambiguous:'BOARD_SCHEMA_INVALID',board_rows_bound:'BOARD_SCHEMA_INVALID',board_schema_changed:'BOARD_SCHEMA_INVALID',
    row_identity_invalid:'BOARD_SCHEMA_INVALID',duplicate_load_id:'BOARD_SCHEMA_INVALID',opener_ambiguous:'OPENER_AMBIGUOUS',
    write_control_denied:'UNSAFE_OPENER',unsafe_opener:'UNSAFE_OPENER',row_binding_invalid:'TAB_STATE_CHANGED',
    row_context_missing:'TAB_STATE_CHANGED',detail_containers_bound:'IDENTITY_BOUND_EXCEEDED',identity_fields_bound:'IDENTITY_BOUND_EXCEEDED',
    detail_container_ambiguous:'DETAIL_IDENTITY_AMBIGUOUS',identity_conflict:'DETAIL_IDENTITY_CONFLICT',
    detail_binding_missing:'DETAIL_IDENTITY_MISSING',provider_binding_missing:'DETAIL_IDENTITY_MISSING'};
  codes.push(...['DIRECT_TARGETS','NEW_CONTAINERS','NEWLY_VISIBLE','CHANGED_SELECTED','IDENTITY_CANDIDATES','OPENER_ATTRIBUTES'].map(c=>'DETAIL_BOUND_'+c));
  globalThis.FreightDeskReadErrors=Object.freeze({safe:error=>{const code=typeof error==='string'?error:error?.message;
    return codes.includes(code)?code:aliases[code]||'READ_EXECUTION_FAILED';}});
})();
